"""empty message

Revision ID: 516882973e57
Revises: 
Create Date: 2021-08-06 15:01:54.412350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516882973e57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img_url', sa.String(length=500), nullable=True),
    sa.Column('ref_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('commodity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img_url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('new_price', sa.String(length=50), nullable=True),
    sa.Column('old_price', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('commodity_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=True),
    sa.Column('img_urls', sa.TEXT(length=5000), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('new_price', sa.String(length=50), nullable=True),
    sa.Column('old_price', sa.String(length=50), nullable=True),
    sa.Column('detail_url', sa.TEXT(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('commodity_style',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=True),
    sa.Column('properties', sa.String(length=255), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('recommend',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img_url', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('ref_code', sa.String(length=255), nullable=True),
    sa.Column('sort_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommend')
    op.drop_table('commodity_style')
    op.drop_table('commodity_detail')
    op.drop_table('commodity')
    op.drop_table('banners')
    # ### end Alembic commands ###
